version: "3.8"
services:
  postgres-mysecret:
    image: postgres:15.5-alpine
    container_name: postgres-mysecret
    restart: always
    environment:
      POSTGRES_PASSWORD: new_password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - .docker:/var/lib/postgresql/data
      
      